platform :ios, '6.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'RegexKitLite'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SVPullToRefresh'
pod 'SDWebImage'
pod 'FMDB'
pod 'EasyTableView'
pod 'OpenUDID'
pod 'pop', '~> 1.0'
 